name: E-Business Backend CI/CD

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend-go

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Docker tag
      run: echo "DOCKER_TAG=$DOCKER_USER/ebusiness-go-backend:$(date +%s)" >> $GITHUB_ENV
        
    - name: Login to the Docker hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_TAG
      
    - name: Push the Docker image
      run: docker push $DOCKER_TAG
