# https://docs.microsoft.com/pl-pl/azure/app-service/deploy-container-github-action?tabs=publish-profile
name: E-Business Frontend CI/CD

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/ebusiness-react-frontend

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend-react

    steps:
    - uses: actions/checkout@v3

    - name: Set backend variable
      run: sed -i 's+http://localhost:8000+https://e-business-mikolaj-backend.azurewebsites.net+g' src/components/RequestSetup.js
           
    - name: Login to the Docker hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build --file Dockerfile -t $DOCKER_IMAGE -t $DOCKER_IMAGE:${{ github.sha }} .
      
    - name: Push the Docker image
      run: docker push $DOCKER_IMAGE --all-tags

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'e-business-mikolaj-frontend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        images: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
